In [212]:
import numpy as np
import pandas as pd
df=pd.read_csv('placementdata.csv')
df

StudentID  CGPA  Internships  Projects  Workshops/Certifications  \
0             1   7.5            1         1                         1   
1             2   8.9            0         3                         2   
2             3   7.3            1         2                         2   
3             4   7.5            1         1                         2   
4             5   8.3            1         2                         2   
...         ...   ...          ...       ...                       ...   
9995       9996   7.5            1         1                         2   
9996       9997   7.4            0         1                         0   
9997       9998   8.4            1         3                         0   
9998       9999   8.9            0         3                         2   
9999      10000   8.4            0         1                         1   

      AptitudeTestScore  SoftSkillsRating ExtracurricularActivities  \
0                    65               4.4                        No   
1                    90               4.0                       Yes   
2                    82               4.8                       Yes   
3                    85               4.4                       Yes   
4                    86               4.5                       Yes   
...                 ...               ...                       ...   
9995                 72               3.9                       Yes   
9996                 90               4.8                        No   
9997                 70               4.8                       Yes   
9998                 87               4.8                       Yes   
9999                 66               3.8                        No   

     PlacementTraining  SSC_Marks  HSC_Marks PlacementStatus  
0                   No         61         79       NotPlaced  
1                  Yes         78         82          Placed  
2                   No         79         80       NotPlaced  
3                  Yes         81         80          Placed  
4                  Yes         74         88          Placed  
...                ...        ...        ...             ...  
9995                No         85         66       NotPlaced  
9996                No         84         67          Placed  
9997               Yes         79         81          Placed  
9998               Yes         71         85          Placed  
9999                No         62         66       NotPlaced  

[10000 rows x 12 columns]

In [213]:
df.head()

StudentID  CGPA  Internships  Projects  Workshops/Certifications  \
0          1   7.5            1         1                         1   
1          2   8.9            0         3                         2   
2          3   7.3            1         2                         2   
3          4   7.5            1         1                         2   
4          5   8.3            1         2                         2   

   AptitudeTestScore  SoftSkillsRating ExtracurricularActivities  \
0                 65               4.4                        No   
1                 90               4.0                       Yes   
2                 82               4.8                       Yes   
3                 85               4.4                       Yes   
4                 86               4.5                       Yes   

  PlacementTraining  SSC_Marks  HSC_Marks PlacementStatus  
0                No         61         79       NotPlaced  
1               Yes         78         82          Placed  
2                No         79         80       NotPlaced  
3               Yes         81         80          Placed  
4               Yes         74         88          Placed

In [214]:
df.tail()

StudentID  CGPA  Internships  Projects  Workshops/Certifications  \
9995       9996   7.5            1         1                         2   
9996       9997   7.4            0         1                         0   
9997       9998   8.4            1         3                         0   
9998       9999   8.9            0         3                         2   
9999      10000   8.4            0         1                         1   

      AptitudeTestScore  SoftSkillsRating ExtracurricularActivities  \
9995                 72               3.9                       Yes   
9996                 90               4.8                        No   
9997                 70               4.8                       Yes   
9998                 87               4.8                       Yes   
9999                 66               3.8                        No   

     PlacementTraining  SSC_Marks  HSC_Marks PlacementStatus  
9995                No         85         66       NotPlaced  
9996                No         84         67          Placed  
9997               Yes         79         81          Placed  
9998               Yes         71         85          Placed  
9999                No         62         66       NotPlaced

In [215]:
df.isna().sum()

StudentID                    0
CGPA                         0
Internships                  0
Projects                     0
Workshops/Certifications     0
AptitudeTestScore            0
SoftSkillsRating             0
ExtracurricularActivities    0
PlacementTraining            0
SSC_Marks                    0
HSC_Marks                    0
PlacementStatus              0
dtype: int64

In [216]:
df.shape

(10000, 12)

In [217]:
df.dtypes

StudentID                      int64
CGPA                         float64
Internships                    int64
Projects                       int64
Workshops/Certifications       int64
AptitudeTestScore              int64
SoftSkillsRating             float64
ExtracurricularActivities     object
PlacementTraining             object
SSC_Marks                      int64
HSC_Marks                      int64
PlacementStatus               object
dtype: object

In [218]:
df['ExtracurricularActivities'].value_counts

<bound method IndexOpsMixin.value_counts of 0        No
1       Yes
2       Yes
3       Yes
4       Yes
       ... 
9995    Yes
9996     No
9997    Yes
9998    Yes
9999     No
Name: ExtracurricularActivities, Length: 10000, dtype: object>

In [219]:
df['PlacementTraining'].value_counts

<bound method IndexOpsMixin.value_counts of 0        No
1       Yes
2        No
3       Yes
4       Yes
       ... 
9995     No
9996     No
9997    Yes
9998    Yes
9999     No
Name: PlacementTraining, Length: 10000, dtype: object>

In [220]:
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
df['ExtracurricularActivities']=lab.fit_transform(df['ExtracurricularActivities'])
df

StudentID  CGPA  Internships  Projects  Workshops/Certifications  \
0             1   7.5            1         1                         1   
1             2   8.9            0         3                         2   
2             3   7.3            1         2                         2   
3             4   7.5            1         1                         2   
4             5   8.3            1         2                         2   
...         ...   ...          ...       ...                       ...   
9995       9996   7.5            1         1                         2   
9996       9997   7.4            0         1                         0   
9997       9998   8.4            1         3                         0   
9998       9999   8.9            0         3                         2   
9999      10000   8.4            0         1                         1   

      AptitudeTestScore  SoftSkillsRating  ExtracurricularActivities  \
0                    65               4.4                          0   
1                    90               4.0                          1   
2                    82               4.8                          1   
3                    85               4.4                          1   
4                    86               4.5                          1   
...                 ...               ...                        ...   
9995                 72               3.9                          1   
9996                 90               4.8                          0   
9997                 70               4.8                          1   
9998                 87               4.8                          1   
9999                 66               3.8                          0   

     PlacementTraining  SSC_Marks  HSC_Marks PlacementStatus  
0                   No         61         79       NotPlaced  
1                  Yes         78         82          Placed  
2                   No         79         80       NotPlaced  
3                  Yes         81         80          Placed  
4                  Yes         74         88          Placed  
...                ...        ...        ...             ...  
9995                No         85         66       NotPlaced  
9996                No         84         67          Placed  
9997               Yes         79         81          Placed  
9998               Yes         71         85          Placed  
9999                No         62         66       NotPlaced  

[10000 rows x 12 columns]

In [221]:
df['PlacementTraining']=lab.fit_transform(df['PlacementTraining'])
df

StudentID  CGPA  Internships  Projects  Workshops/Certifications  \
0             1   7.5            1         1                         1   
1             2   8.9            0         3                         2   
2             3   7.3            1         2                         2   
3             4   7.5            1         1                         2   
4             5   8.3            1         2                         2   
...         ...   ...          ...       ...                       ...   
9995       9996   7.5            1         1                         2   
9996       9997   7.4            0         1                         0   
9997       9998   8.4            1         3                         0   
9998       9999   8.9            0         3                         2   
9999      10000   8.4            0         1                         1   

      AptitudeTestScore  SoftSkillsRating  ExtracurricularActivities  \
0                    65               4.4                          0   
1                    90               4.0                          1   
2                    82               4.8                          1   
3                    85               4.4                          1   
4                    86               4.5                          1   
...                 ...               ...                        ...   
9995                 72               3.9                          1   
9996                 90               4.8                          0   
9997                 70               4.8                          1   
9998                 87               4.8                          1   
9999                 66               3.8                          0   

      PlacementTraining  SSC_Marks  HSC_Marks PlacementStatus  
0                     0         61         79       NotPlaced  
1                     1         78         82          Placed  
2                     0         79         80       NotPlaced  
3                     1         81         80          Placed  
4                     1         74         88          Placed  
...                 ...        ...        ...             ...  
9995                  0         85         66       NotPlaced  
9996                  0         84         67          Placed  
9997                  1         79         81          Placed  
9998                  1         71         85          Placed  
9999                  0         62         66       NotPlaced  

[10000 rows x 12 columns]

In [222]:
df.dtypes

StudentID                      int64
CGPA                         float64
Internships                    int64
Projects                       int64
Workshops/Certifications       int64
AptitudeTestScore              int64
SoftSkillsRating             float64
ExtracurricularActivities      int64
PlacementTraining              int64
SSC_Marks                      int64
HSC_Marks                      int64
PlacementStatus               object
dtype: object

In [223]:
x=df.iloc[:,:-1].values
x

array([[1.000e+00, 7.500e+00, 1.000e+00, ..., 0.000e+00, 6.100e+01,
        7.900e+01],
       [2.000e+00, 8.900e+00, 0.000e+00, ..., 1.000e+00, 7.800e+01,
        8.200e+01],
       [3.000e+00, 7.300e+00, 1.000e+00, ..., 0.000e+00, 7.900e+01,
        8.000e+01],
       ...,
       [9.998e+03, 8.400e+00, 1.000e+00, ..., 1.000e+00, 7.900e+01,
        8.100e+01],
       [9.999e+03, 8.900e+00, 0.000e+00, ..., 1.000e+00, 7.100e+01,
        8.500e+01],
       [1.000e+04, 8.400e+00, 0.000e+00, ..., 0.000e+00, 6.200e+01,
        6.600e+01]], shape=(10000, 11))

In [224]:
y=df.iloc[:,-1].values
y

array(['NotPlaced', 'Placed', 'NotPlaced', ..., 'Placed', 'Placed',
       'NotPlaced'], shape=(10000,), dtype=object)

In [225]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=1)
x_train

array([[2.229e+03, 8.000e+00, 1.000e+00, ..., 1.000e+00, 7.200e+01,
        8.400e+01],
       [5.911e+03, 6.700e+00, 1.000e+00, ..., 0.000e+00, 8.600e+01,
        6.900e+01],
       [1.951e+03, 7.500e+00, 1.000e+00, ..., 1.000e+00, 8.200e+01,
        7.400e+01],
       ...,
       [9.060e+02, 7.600e+00, 0.000e+00, ..., 0.000e+00, 7.400e+01,
        6.700e+01],
       [5.193e+03, 6.500e+00, 1.000e+00, ..., 0.000e+00, 5.800e+01,
        7.200e+01],
       [2.360e+02, 8.200e+00, 2.000e+00, ..., 1.000e+00, 7.700e+01,
        8.200e+01]], shape=(7000, 11))

In [226]:
x_test

array([[9.954e+03, 8.400e+00, 2.000e+00, ..., 1.000e+00, 7.900e+01,
        8.500e+01],
       [3.851e+03, 8.500e+00, 2.000e+00, ..., 1.000e+00, 8.300e+01,
        8.100e+01],
       [4.963e+03, 9.100e+00, 1.000e+00, ..., 0.000e+00, 5.500e+01,
        6.200e+01],
       ...,
       [8.985e+03, 8.400e+00, 0.000e+00, ..., 0.000e+00, 6.200e+01,
        6.400e+01],
       [6.499e+03, 6.600e+00, 1.000e+00, ..., 0.000e+00, 5.800e+01,
        6.200e+01],
       [6.328e+03, 7.600e+00, 0.000e+00, ..., 1.000e+00, 5.500e+01,
        7.300e+01]], shape=(3000, 11))

In [227]:
y_train

array(['NotPlaced', 'NotPlaced', 'NotPlaced', ..., 'NotPlaced',
       'NotPlaced', 'NotPlaced'], shape=(7000,), dtype=object)

In [228]:
y_test

array(['Placed', 'Placed', 'Placed', ..., 'Placed', 'NotPlaced',
       'NotPlaced'], shape=(3000,), dtype=object)

In [229]:
from sklearn.preprocessing import MinMaxScaler
scalar=MinMaxScaler()
scalar.fit(x_train)
x_train=scalar.transform(x_train)
x_test=scalar.transform(x_test)
x_train

array([[0.22282228, 0.6       , 0.5       , ..., 1.        , 0.48571429,
        0.87096774],
       [0.59105911, 0.08      , 0.5       , ..., 0.        , 0.88571429,
        0.38709677],
       [0.1950195 , 0.4       , 0.5       , ..., 1.        , 0.77142857,
        0.5483871 ],
       ...,
       [0.09050905, 0.44      , 0.        , ..., 0.        , 0.54285714,
        0.32258065],
       [0.51925193, 0.        , 0.5       , ..., 0.        , 0.08571429,
        0.48387097],
       [0.02350235, 0.68      , 1.        , ..., 1.        , 0.62857143,
        0.80645161]], shape=(7000, 11))

In [230]:
# from sklearn.svm import SVC
# model=SVC()
# model.fit(x_train,y_train)
# y_pred=model.predict(x_test)
# y_pred

In [231]:
# from sklearn.metrics import confusion_matrix
# cm=confusion_matrix(y_pred,y_test)
# cm

In [232]:
# from sklearn.metrics import accuracy_score
# score=accuracy_score(y_pred,y_test)
# score

In [233]:
# from sklearn.metrics import classification_report
# cr=classification_report(y_pred,y_test)
# print(cr)

In [234]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
knn=KNeighborsClassifier(n_neighbors=7)
bayes=MultinomialNB()
sup=SVC()
lst=[knn,bayes,sup]

In [ ]:
for i in lst:
    i.fit(x_train,y_train)
    y_pred=i.predict(x_test)
    cm=confusion_matrix(y_pred,y_test)
    print(cm)
    score=accuracy_score(y_pred,y_test)
    print(score)
    cr=classification_report(y_pred,y_test)

[[1447  319]
 [ 307  927]]
0.7913333333333333
              precision    recall  f1-score   support

   NotPlaced       0.82      0.82      0.82      1766
      Placed       0.74      0.75      0.75      1234

    accuracy                           0.79      3000
   macro avg       0.78      0.79      0.78      3000
weighted avg       0.79      0.79      0.79      3000

[[1629  954]
 [ 125  292]]
0.6403333333333333
              precision    recall  f1-score   support

   NotPlaced       0.93      0.63      0.75      2583
      Placed       0.23      0.70      0.35       417

    accuracy                           0.64      3000
   macro avg       0.58      0.67      0.55      3000
weighted avg       0.83      0.64      0.70      3000

[[1468  297]
 [ 286  949]]
0.8056666666666666
              precision    recall  f1-score   support

   NotPlaced       0.84      0.83      0.83      1765
      Placed       0.76      0.77      0.77      1235

    accuracy                           0.81 

In [237]:
df["PlacementStatus"].value_counts()

PlacementStatus
NotPlaced    5803
Placed       4197
Name: count, dtype: int64

In [ ]:
# from imblearn.over_sampling import SMOTE
# from collections import Counter
# smote=SMOTE(random_state=42)
# x_resampled,y_resampled=smote.fit_resample(x,y)
# print(Counter(y_resampled))

SyntaxError: invalid non-printable character U+00A0 (3264656995.py, line 2)